protoc --cpp_out=. -I=. ./simple_hello.proto 
protoc --grpc_out=. --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin simple_hello.proto 

protoc --cpp_out=. -I=. ./healthCheck.proto 
protoc --grpc_out=. --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin healthCheck.proto 

g++ -std=c++17 -c simple_hello.grpc.pb.cc simple_hello.pb.cc simple_client.cc simple_server.cc healthCheck.grpc.pb.cc healthCheck.pb.cc
g++ -std=c++17 -o client_multi simple_hello.grpc.pb.o simple_hello.pb.o healthCheck.grpc.pb.o healthCheck.pb.o simple_client.o /usr/local/lib/libgrpc++_reflection.a /usr/local/lib/libgrpc++.a /usr/local/lib/libprotobuf.a /usr/local/lib/libgrpc.a /usr/local/lib/libz.a /usr/local/lib/libcares.a /usr/local/lib/libaddress_sorting.a /usr/local/lib/libre2.a /usr/local/lib/libabsl_raw_hash_set.a /usr/local/lib/libabsl_hashtablez_sampler.a /usr/local/lib/libabsl_hash.a /usr/local/lib/libabsl_city.a /usr/local/lib/libabsl_low_level_hash.a /usr/local/lib/libabsl_statusor.a /usr/local/lib/libabsl_bad_variant_access.a /usr/local/lib/libgpr.a /usr/local/lib/libupb.a /usr/local/lib/libabsl_status.a /usr/local/lib/libabsl_cord.a /usr/local/lib/libabsl_bad_optional_access.a /usr/local/lib/libabsl_cordz_info.a /usr/local/lib/libabsl_cord_internal.a /usr/local/lib/libabsl_cordz_functions.a /usr/local/lib/libabsl_exponential_biased.a /usr/local/lib/libabsl_cordz_handle.a /usr/local/lib/libabsl_str_format_internal.a /usr/local/lib/libabsl_synchronization.a /usr/local/lib/libabsl_stacktrace.a /usr/local/lib/libabsl_symbolize.a /usr/local/lib/libabsl_debugging_internal.a /usr/local/lib/libabsl_demangle_internal.a /usr/local/lib/libabsl_graphcycles_internal.a /usr/local/lib/libabsl_malloc_internal.a /usr/local/lib/libabsl_time.a /usr/local/lib/libabsl_strings.a /usr/local/lib/libabsl_throw_delegate.a /usr/local/lib/libabsl_int128.a /usr/local/lib/libabsl_strings_internal.a /usr/local/lib/libabsl_base.a /usr/local/lib/libabsl_spinlock_wait.a /usr/local/lib/libabsl_raw_logging_internal.a /usr/local/lib/libabsl_log_severity.a /usr/local/lib/libabsl_civil_time.a /usr/local/lib/libabsl_time_zone.a -framework CoreFoundation /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a 
#g++ -std=c++17 -o server simple_hello.grpc.pb.o simple_hello.pb.o healthCheck.grpc.pb.o healthCheck.pb.o simple_server.o /usr/local/lib/libgrpc++_reflection.a /usr/local/lib/libgrpc++.a /usr/local/lib/libprotobuf.a /usr/local/lib/libgrpc.a /usr/local/lib/libz.a /usr/local/lib/libcares.a /usr/local/lib/libaddress_sorting.a /usr/local/lib/libre2.a /usr/local/lib/libabsl_raw_hash_set.a /usr/local/lib/libabsl_hashtablez_sampler.a /usr/local/lib/libabsl_hash.a /usr/local/lib/libabsl_city.a /usr/local/lib/libabsl_low_level_hash.a /usr/local/lib/libabsl_statusor.a /usr/local/lib/libabsl_bad_variant_access.a /usr/local/lib/libgpr.a /usr/local/lib/libupb.a /usr/local/lib/libabsl_status.a /usr/local/lib/libabsl_cord.a /usr/local/lib/libabsl_bad_optional_access.a /usr/local/lib/libabsl_cordz_info.a /usr/local/lib/libabsl_cord_internal.a /usr/local/lib/libabsl_cordz_functions.a /usr/local/lib/libabsl_exponential_biased.a /usr/local/lib/libabsl_cordz_handle.a /usr/local/lib/libabsl_str_format_internal.a /usr/local/lib/libabsl_synchronization.a /usr/local/lib/libabsl_stacktrace.a /usr/local/lib/libabsl_symbolize.a /usr/local/lib/libabsl_debugging_internal.a /usr/local/lib/libabsl_demangle_internal.a /usr/local/lib/libabsl_graphcycles_internal.a /usr/local/lib/libabsl_malloc_internal.a /usr/local/lib/libabsl_time.a /usr/local/lib/libabsl_strings.a /usr/local/lib/libabsl_throw_delegate.a /usr/local/lib/libabsl_int128.a /usr/local/lib/libabsl_strings_internal.a /usr/local/lib/libabsl_base.a /usr/local/lib/libabsl_spinlock_wait.a /usr/local/lib/libabsl_raw_logging_internal.a /usr/local/lib/libabsl_log_severity.a /usr/local/lib/libabsl_civil_time.a /usr/local/lib/libabsl_time_zone.a -framework CoreFoundation /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a 
