// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: simple_hello.proto

#include "simple_hello.pb.h"
#include "simple_hello.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace simple {

static const char* RequestService_method_names[] = {
  "/simple.RequestService/rService",
  "/simple.RequestService/Check",
  "/simple.RequestService/Watch",
};

std::unique_ptr< RequestService::Stub> RequestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RequestService::Stub> stub(new RequestService::Stub(channel, options));
  return stub;
}

RequestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_rService_(RequestService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Check_(RequestService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Watch_(RequestService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status RequestService::Stub::rService(::grpc::ClientContext* context, const ::simple::Request& request, ::simple::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::simple::Request, ::simple::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_rService_, context, request, response);
}

void RequestService::Stub::async::rService(::grpc::ClientContext* context, const ::simple::Request* request, ::simple::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::simple::Request, ::simple::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_rService_, context, request, response, std::move(f));
}

void RequestService::Stub::async::rService(::grpc::ClientContext* context, const ::simple::Request* request, ::simple::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_rService_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::simple::Response>* RequestService::Stub::PrepareAsyncrServiceRaw(::grpc::ClientContext* context, const ::simple::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::simple::Response, ::simple::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_rService_, context, request);
}

::grpc::ClientAsyncResponseReader< ::simple::Response>* RequestService::Stub::AsyncrServiceRaw(::grpc::ClientContext* context, const ::simple::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncrServiceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RequestService::Stub::Check(::grpc::ClientContext* context, const ::simple::HealthCheckRequest& request, ::simple::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::simple::HealthCheckRequest, ::simple::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Check_, context, request, response);
}

void RequestService::Stub::async::Check(::grpc::ClientContext* context, const ::simple::HealthCheckRequest* request, ::simple::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::simple::HealthCheckRequest, ::simple::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, std::move(f));
}

void RequestService::Stub::async::Check(::grpc::ClientContext* context, const ::simple::HealthCheckRequest* request, ::simple::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Check_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::simple::HealthCheckResponse>* RequestService::Stub::PrepareAsyncCheckRaw(::grpc::ClientContext* context, const ::simple::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::simple::HealthCheckResponse, ::simple::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Check_, context, request);
}

::grpc::ClientAsyncResponseReader< ::simple::HealthCheckResponse>* RequestService::Stub::AsyncCheckRaw(::grpc::ClientContext* context, const ::simple::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::simple::HealthCheckResponse>* RequestService::Stub::WatchRaw(::grpc::ClientContext* context, const ::simple::HealthCheckRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::simple::HealthCheckResponse>::Create(channel_.get(), rpcmethod_Watch_, context, request);
}

void RequestService::Stub::async::Watch(::grpc::ClientContext* context, const ::simple::HealthCheckRequest* request, ::grpc::ClientReadReactor< ::simple::HealthCheckResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::simple::HealthCheckResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Watch_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::simple::HealthCheckResponse>* RequestService::Stub::AsyncWatchRaw(::grpc::ClientContext* context, const ::simple::HealthCheckRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::simple::HealthCheckResponse>::Create(channel_.get(), cq, rpcmethod_Watch_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::simple::HealthCheckResponse>* RequestService::Stub::PrepareAsyncWatchRaw(::grpc::ClientContext* context, const ::simple::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::simple::HealthCheckResponse>::Create(channel_.get(), cq, rpcmethod_Watch_, context, request, false, nullptr);
}

RequestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RequestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RequestService::Service, ::simple::Request, ::simple::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RequestService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::simple::Request* req,
             ::simple::Response* resp) {
               return service->rService(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RequestService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RequestService::Service, ::simple::HealthCheckRequest, ::simple::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RequestService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::simple::HealthCheckRequest* req,
             ::simple::HealthCheckResponse* resp) {
               return service->Check(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RequestService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< RequestService::Service, ::simple::HealthCheckRequest, ::simple::HealthCheckResponse>(
          [](RequestService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::simple::HealthCheckRequest* req,
             ::grpc::ServerWriter<::simple::HealthCheckResponse>* writer) {
               return service->Watch(ctx, req, writer);
             }, this)));
}

RequestService::Service::~Service() {
}

::grpc::Status RequestService::Service::rService(::grpc::ServerContext* context, const ::simple::Request* request, ::simple::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RequestService::Service::Check(::grpc::ServerContext* context, const ::simple::HealthCheckRequest* request, ::simple::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RequestService::Service::Watch(::grpc::ServerContext* context, const ::simple::HealthCheckRequest* request, ::grpc::ServerWriter< ::simple::HealthCheckResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace simple

